version: "3.7"

services:

  pg_db:
    container_name: pg_container
    image: postgres:15
    restart: always
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./.env
    depends_on:
      pg_db:
        condition: service_healthy
    ports:
      - "5050:5050"

  python_extractload:
    container_name: python_extload
    build: extract_load/.
    image: python_el
    env_file:
      - ./.env
    depends_on:
      pg_db:
        condition: service_healthy

  dbt:
    container_name: dbt
    build: dbt/.
    image: dbt-dev
    env_file:
      - ./.env
    depends_on:
      pg_db:
        condition: service_healthy
      python_extractload:
        condition: service_completed_successfully

volumes:
  pgdata:
