dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: pg_container
      user: postgres
      password: postgres
      port: 5432
      dbname: globalmarket
      schema: analytics
      threads: 1