dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres_container
      user: postgres
      password: postgres
      port: 5432
      dbname: dbt_dev
      schema: raw_data
      threads: 1